### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by BechtelCanDoIt** [rickwargo/alexa-skill-template#1]
Sorry if I'm way off base here, I'm not to node.js and trying to get started with this.

Should this
AWS Template Installation

```
Copy from Template using git://github.com/rickwargo/template.git.
```

Really be this?
AWS Template Installation

```
npm install rickwargo/alexa-skill-template --save
```

**Comment by rickwargo** [comment]
Scott, this is an interim solution. I'll be pushing another version in a day or two. I' trying to incorporate my changes to Matt Kruse's alexa-app and alexa-app-server with my environment. This will be a different repository. I wanted to make sure it is working well before publicizing it. This is not designed to be a node module, just a clone of the git repo.
